installing_message = "Built by <b>Elvin Stonks</b>, Version <b>Bing Chilling</b>"

[[packages]]
name = "yuzu Mainline"
description = "Includes frequent updates to yuzu with all the latest reviewed and tested features."
default = false
    [packages.source]
    name = "github"
    match = "^yuzu-windows-msvc-[0-9]*-[0-9a-f]*.tar.xz$"
        [packages.source.config]
        repo = "yuzu-emu/yuzu-mainline"
    [[packages.shortcuts]]
    name = "yuzu"
    relative_path = "yuzu-windows-msvc/yuzu.exe"
    description = "Launch yuzu"
    
[[packages]]
name = "yuzu Early Access"
description = "Preview release with the newest features. But you can download it for free thanks to the generous messiah charl."
default = true
    [packages.source]
    name = "github"
    match = "^yuzu-early-access-EA[0-9]*.zip$"
        [packages.source.config]
        repo = "Kryptuq/Yuzu-Early-Access-files"
    [[packages.shortcuts]]
    name = "yuzu Early Access"
    relative_path = "yuzu-early-access/yuzu.exe"
    description = "Launch yuzu Early Access"